import { StyleSheet, Platform, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export const DashboardStyles = (
    theme: any,
    isDark: boolean,
    subTextColor: string,
    borderColor: string,
    inputBg: string
) =>
    StyleSheet.create({
        container: { flex: 1 },
        headerControls: { padding: 16, alignItems: 'flex-end' },
        verificationButton: {
            backgroundColor: '#10B981',
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 20,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        verificationButtonText: { color: '#FFF', fontWeight: '600' },
        mapContainer: {
            flex: 1,
            marginHorizontal: 16,
            borderRadius: 16,
            overflow: 'hidden',
            borderWidth: 1,
            position: 'relative',
        },
        layersButton: {
            position: 'absolute',
            top: 20,
            right: 12,
            padding: 10,
            borderRadius: 25,
            elevation: 5,
        },
        fabContainer: {
            position: 'absolute',
            left: 16,
            top: 20,
            gap: 12,
            alignItems: 'center',
            zIndex: 10,
        },
        fab: {
            backgroundColor: '#007AFF',
            width: 44,
            height: 44,
            borderRadius: 22,
            justifyContent: 'center',
            alignItems: 'center',
            elevation: 4,
        },
        modalOverlayCenter: {
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.6)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        bottomSheetHeader: {
            padding: 16,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        directionsButton: {
            backgroundColor: '#34C759',
            padding: 8,
            borderRadius: 8,
            flexDirection: 'row',
            gap: 5,
        },
        attributeRow: { marginBottom: 15 },
        modalOverlay: {
            flex: 1,
            justifyContent: 'flex-end',
            backgroundColor: 'rgba(0,0,0,0.45)',
        },
        bottomSheet: {
            borderTopLeftRadius: 22,
            borderTopRightRadius: 22,
            paddingHorizontal: 20,
            paddingTop: 10,
            maxHeight: '75%',
            elevation: 20,
        },
        searchModal: {
            width: '100%',
            borderRadius: 16,
            padding: 20,
        },
        dropdown: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: 14,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E5E7EB',
            backgroundColor: isDark ? '#2E3147' : '#FFFFFF',
        },
        dropdownList: {
            marginTop: 6,
            borderRadius: 10,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#ccc',
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
        },
        tabSelector: {
            flexDirection: 'row',
            borderBottomWidth: 1,
            width: '100%',
        },
        tabForStp: {
            paddingVertical: 12,
            paddingHorizontal: 12,
            alignItems: 'center',
            justifyContent: 'center',
        },
        tab: {
            paddingVertical: 12,
            paddingHorizontal: 12,
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
        },
        activeTab: {
            borderBottomWidth: 2,
            borderBottomColor: '#007AFF',
        },
        tabTextNotForSTP: {
            fontSize: 12,
            fontWeight: '600',
            color: theme.text,
        },
        tabText: {
            fontSize: 12,
            fontWeight: '600',
            color: theme.text,
        },
        attributeValue: {
            padding: 12,
            borderRadius: 4,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            backgroundColor: isDark ? '#2E3147' : '#F8FAFC',
            marginTop: 4,
        },
        searchInputWrapper: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 12,
            paddingVertical: 10,
            borderRadius: 10,
            borderWidth: 1,
            marginTop: 12,
            marginBottom: 12,
        },
        schematicWrapper: {
            height: 250,
            width: '100%',
            backgroundColor: isDark ? '#1E2130' : '#fff',
            borderRadius: 12,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
        },
        schematicBg: {
            flex: 1,
            width: '100%',
            height: '100%',
        },
        floatingTag: {
            position: 'absolute',
            backgroundColor: isDark ? 'rgba(30,33,48,0.8)' : 'rgba(255, 255, 255, 0.7)',
            paddingHorizontal: 4,
            padding: 2,
        },
        centerTagContainer: {
            position: 'absolute',
            top: '40%',
            backgroundColor: isDark ? 'rgba(30,33,48,0.8)' : 'rgba(255, 255, 255, 0.7)',

            left: '40%',
            alignItems: 'center',
            transform: [{ rotate: '19deg' }],
        },
        tagLabelText: {
            fontSize: 12,
            fontWeight: '700',
            color: isDark ? '#E2E8F0' : '#000',
        },
        pipeNameText: {
            fontSize: 13,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#000',
            marginBottom: 2,
        },
        searchInput: {
            flex: 1,
            marginLeft: 8,
            fontSize: 14,
            color: theme.text,
        },
        card: {
            padding: 16,
            borderRadius: 16,
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: isDark ? 0.3 : 0.08,
            shadowRadius: 8,
            marginTop: 20,
            elevation: 4,
        },
        sectionTitle: {
            fontSize: 16,
            fontWeight: '800',
            marginBottom: 12,
            color: isDark ? '#FFFFFF' : '#0F172A',
            letterSpacing: 0.3,
        },
        kvKey: {
            fontSize: 14,
            color: isDark ? '#94A3B8' : '#475569',
            fontWeight: '600',
            marginBottom: 2,
        },
        kvValue: {
            fontSize: 14,
            color: isDark ? '#E2E8F0' : '#1E293B',
            fontWeight: '500',
        },
        loaderOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.6)',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 10000,
        },
        loaderContent: {
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            padding: 30,
            borderRadius: 20,
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.25,
            shadowRadius: 10,
            elevation: 10,
        },
        loaderMessage: {
            marginTop: 15,
            fontSize: 18,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#1E293B',
        },
        loaderSubMessage: {
            marginTop: 4,
            fontSize: 12,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: '500',
        },
        linkText: {
            fontSize: 14,
            color: isDark ? '#E2E8F0' : '#1E293B',
            fontWeight: '600',
            marginBottom: 4,
        },
        tagContainer: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            marginTop: 10,
            paddingTop: 8,
            borderTopWidth: 1,
            borderTopColor: isDark ? '#3A3D4E' : '#F1F5F9',
        },
        tagBadge: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? '#2E3147' : '#F1F5F9',
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            marginRight: 8,
            marginBottom: 4,
        },
        tagText: {
            fontSize: 11,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: '700',
        },
        statusBadgeContainer: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
            marginTop: 10,
        },
        statusBadge: {
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 20,
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: 80,
        },
        statusBadgeText: {
            fontSize: 14,
            fontWeight: '700',
        },
        pipeLine: {
            width: '110%',
            height: 16,
            borderTopWidth: 2,
            borderBottomWidth: 2,
            borderColor: isDark ? '#64748B' : '#334155',
            backgroundColor: isDark ? '#475569' : '#94A3B8',
        },
        saveButton: {
            backgroundColor: '#007AFF',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 14,
            borderRadius: 12,
            marginTop: 10,
            gap: 10,
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
        },
        saveButtonText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: '700',
        },
        linkRow: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: 12,
            backgroundColor: isDark ? '#2E3147' : '#F8FAFC',
            borderRadius: 10,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
        },
        linkTextPrimary: {
            flex: 1,
            marginLeft: 12,
            fontSize: 14,
            fontWeight: '600',
            color: isDark ? '#E2E8F0' : '#1E293B',
        },
        subLabel: {
            fontSize: 10,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: 'bold',
            marginBottom: 2,
        },
        dragHandle: {
            width: 40,
            height: 4,
            borderRadius: 2,
            backgroundColor: isDark ? '#3A3D4E' : '#CBD5E1',
            alignSelf: 'center',
            marginBottom: 12,
        },
        linkCard: {
            padding: 16,
            borderRadius: 14,
            marginBottom: 12,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: isDark ? 0.2 : 0.05,
            shadowRadius: 4,
            elevation: 2,
        },
        iconBadgeBlue: {
            width: 40,
            height: 40,
            borderRadius: 10,
            backgroundColor: isDark ? '#1E3A5F' : '#E0F2FE',
            alignItems: 'center',
            justifyContent: 'center',
        },
        iconBadgeOrange: {
            width: 36,
            height: 36,
            borderRadius: 8,
            backgroundColor: isDark ? '#3D2B00' : '#FEF3C7',
            justifyContent: 'center',
            alignItems: 'center',
        },
        linkPrimaryText: {
            fontSize: 14,
            fontWeight: '600',
            letterSpacing: 0.2,
            color: isDark ? '#E2E8F0' : '#1E293B',
        },
        linkMetaText: {
            fontSize: 12,
            color: isDark ? '#64748B' : '#94A3B8',
            fontWeight: '500',
        },
        execCard: {
            padding: 16,
            borderRadius: 16,
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            marginBottom: 14,
            borderLeftWidth: 4,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 3 },
            shadowOpacity: isDark ? 0.25 : 0.06,
            shadowRadius: 6,
            elevation: 3,
        },
        execHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 14,
        },
        execStatusText: {
            fontSize: 15,
            fontWeight: '700',
            color: isDark ? '#FFFFFF' : '#0F172A',
        },
        statusPill: {
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
        },
        statusPillText: {
            fontSize: 11,
            fontWeight: '700',
            color: '#15803D',
        },
        execGrid: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            gap: 12,
            marginTop: 8,
        },
        execField: { flex: 1 },
        execLabel: {
            fontSize: 11,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: '700',
            marginBottom: 6,
            textAlign: 'center',
        },
        inputContainer: {
            height: 40,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            backgroundColor: isDark ? '#2E3147' : '#F8FAFC',
            justifyContent: 'center',
            alignItems: 'center',
            ...Platform.select({
                ios: {
                    shadowColor: '#000',
                    shadowOffset: { width: 0, height: 1 },
                    shadowOpacity: 0.05,
                    shadowRadius: 2,
                },
                android: { elevation: 1 },
            }),
        },
        execValueText: {
            fontSize: 14,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#1E293B',
        },
        containerRemark: {
            padding: 15,
            backgroundColor: isDark ? '#1E2130' : '#f9f9f9',
        },
        addRemarkContainer: {
            backgroundColor: isDark ? '#252836' : '#fff',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#e0e0e0',
            borderRadius: 8,
            padding: 15,
            marginBottom: 20,
        },
        sectionTitleRemark: {
            fontSize: 16,
            fontWeight: '600',
            marginBottom: 10,
            color: isDark ? '#E2E8F0' : '#333',
        },
        textInput: {
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#ccc',
            borderRadius: 4,
            padding: 10,
            height: 100,
            backgroundColor: isDark ? '#252836' : '#fff',
            fontSize: 14,
            color: isDark ? '#E2E8F0' : '#000',
        },
        addButton: {
            backgroundColor: '#007AFF',
            padding: 12,
            borderRadius: 4,
            marginTop: 10,
            alignItems: 'center',
            justifyContent: 'center',
            width: 120,
        },
        disabledButton: { backgroundColor: isDark ? '#3A3A3C' : '#cccccc' },
        addButtonText: { color: '#fff', fontWeight: 'bold' },
        historyContainer: { marginTop: 10 },
        remarkCard: {
            backgroundColor: isDark ? '#252836' : '#fff',
            padding: 12,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#eee',
            marginBottom: 10,
        },
        remarkUser: {
            fontWeight: 'bold',
            color: isDark ? '#94A3B8' : '#555',
            marginBottom: 2,
        },
        emptyText: {
            textAlign: 'center',
            color: isDark ? '#64748B' : '#999',
            marginTop: 20,
        },
        layerCard: {
            backgroundColor: isDark ? '#252836' : '#fff',
            borderRadius: 12,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E5E7EB',
            padding: 12,
            marginBottom: 16,
        },
        layerCardHeader: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        cardHeader: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        layerNameText: {
            fontSize: 16,
            fontWeight: '700',
            color: isDark ? '#E2E8F0' : '#000000',
        },
        layerSubtext: {
            fontSize: 12,
            color: isDark ? '#64748B' : '#6B7280',
            marginTop: 2,
        },
        customToggle: {
            width: 60,
            height: 32,
            borderRadius: 16,
            justifyContent: 'center',
            alignItems: 'center',
        },
        customToggleText: {
            color: '#fff',
            fontSize: 14,
            fontWeight: '800',
        },
        legendContainer: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 12,
            marginBottom: 12,
        },
        legendItem: {
            flexDirection: 'row',
            alignItems: 'center',
            width: '45%',
        },
        dot: {
            width: 8,
            height: 8,
            borderRadius: 4,
            marginRight: 6,
            backgroundColor: isDark ? '#94A3B8' : '#374151',
        },
        legendText: {
            fontSize: 12,
            color: isDark ? '#94A3B8' : '#374151',
        },
        layerFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            paddingTop: 10,
            borderTopWidth: 1,
            borderTopColor: isDark ? '#3A3D4E' : '#F3F4F6',
        },
        footerLabel: {
            fontSize: 12,
            color: isDark ? '#64748B' : '#9CA3AF',
        },
        stateLabel: {
            fontSize: 12,
            fontWeight: '700',
            color: theme.text,
        },
        unitCard: {
            marginVertical: 8,
            padding: 16,
            borderRadius: 12,
            borderWidth: 1,
            elevation: 2,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: isDark ? 0.2 : 0.1,
            shadowRadius: 3,
        },
        unitCardHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 12,
        },
        unitTitle: {
            fontSize: 16,
            fontWeight: '800',
            flex: 1,
            color: isDark ? '#E2E8F0' : '#0F172A',
        },
        metricItem: {
            alignItems: 'center',
            flex: 1,
        },
        metricLabel: {
            fontSize: 9,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: '700',
            textTransform: 'uppercase',
        },
        progressRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        progressBarBg: {
            height: 8,
            backgroundColor: isDark ? '#2E3147' : '#E2E8F0',
            borderRadius: 4,
            marginTop: 4,
            overflow: 'hidden',
        },
        progressBarFill: {
            height: '100%',
            backgroundColor: '#10B981',
        },
        progressText: {
            fontSize: 14,
            fontWeight: '800',
            minWidth: 40,
            color: theme.text,
        },
        subActivityToggle: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            marginTop: 12,
            paddingTop: 12,
            borderTopWidth: 1,
            borderTopColor: isDark ? '#3A3D4E' : '#F1F5F9',
            gap: 4,
        },
        subActivityCard: {
            padding: 12,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            borderLeftWidth: 4,
            marginTop: 10,
            borderLeftColor: '#007AFF',
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
        },
        subActivityCard2: {
            padding: 12,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: isDark ? 0.2 : 0.05,
            shadowRadius: 2,
            elevation: 2,
        },
        remarkText: {
            fontSize: 12,
            color: isDark ? '#94A3B8' : '#475569',
            fontStyle: 'italic',
        },
        unitDetailImage: {
            width: '100%',
            height: 120,
            borderRadius: 8,
            marginBottom: 12,
        },
        imagePlaceholderSmall: {
            width: '100%',
            height: 40,
            backgroundColor: isDark ? '#2E3147' : '#F1F5F9',
            borderRadius: 8,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 12,
        },
        mechRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingTop: 8,
            borderTopWidth: 1,
            borderTopColor: isDark ? '#3A3D4E' : '#F1F5F9',
        },
        subActivityDetails: {
            flexDirection: 'row',
            marginTop: 4,
            marginBottom: 8,
        },
        editToggleButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 8,
            paddingHorizontal: 16,
            borderRadius: 20,
            elevation: 2,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 2,
        },
        actionRow: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            marginBottom: 16,
            paddingHorizontal: 4,
        },
        actionButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 12,
            paddingHorizontal: 24,
            borderRadius: 25,
            borderWidth: 1.5,
            minWidth: 150,
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
        },
        editButton: {
            backgroundColor: isDark ? '#1E3A5F' : '#F0F7FF',
            borderColor: '#007AFF',
        },
        editButtonText: {
            color: '#007AFF',
            fontWeight: '800',
            fontSize: 14,
            marginLeft: 8,
        },
        saveButtonAction: {
            backgroundColor: '#10B981',
            borderColor: '#10B981',
        },
        saveButtonTextAction: {
            color: '#FFF',
            fontWeight: '700',
            fontSize: 13,
            marginLeft: 4,
        },
        cancelButton: {
            backgroundColor: isDark ? '#3D1515' : '#FFF1F2',
            borderColor: '#EF4444',
        },
        cancelButtonText: {
            color: '#EF4444',
            fontWeight: '700',
            fontSize: 13,
            marginLeft: 4,
        },
        attributeInput: {
            padding: 12,
            borderRadius: 10,
            borderWidth: 1.5,
            borderColor: '#007AFF',
            marginTop: 6,
            fontSize: 14,
            fontWeight: '600',
            backgroundColor: isDark ? '#1E2130' : '#FFFFFF',
            color: isDark ? '#E2E8F0' : '#000000',
        },
        centeredActionContainer: {
            marginTop: 20,
            marginBottom: 20,
            alignItems: 'center',
            width: '100%',
        },
        buttonGroup: {
            flexDirection: 'row',
            gap: 12,
        },
        tagWrapper: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            marginTop: 12,
            paddingTop: 12,
            borderTopWidth: 1,
            borderTopColor: isDark ? '#3A3D4E' : '#F1F5F9',
            gap: 6,
        },
        addNewButton: {
            backgroundColor: '#007AFF',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 12,
            borderRadius: 12,
            marginBottom: 16,
            gap: 8,
        },
        addNewButtonText: {
            color: '#FFF',
            fontWeight: 'bold',
            fontSize: 14,
        },
        viewImageButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: isDark ? '#1E3A5F' : '#EBF5FF',
            paddingVertical: 12,
            borderRadius: 10,
            marginBottom: 12,
            borderWidth: 1,
            borderColor: '#007AFF',
            gap: 8,
        },
        viewImageButtonText: {
            color: '#007AFF',
            fontSize: 14,
            fontWeight: '700',
        },
        noImagePlaceholder: {
            paddingVertical: 10,
            alignItems: 'center',
            backgroundColor: isDark ? '#2E3147' : '#F8FAFC',
            borderRadius: 8,
            marginBottom: 12,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            borderStyle: 'dashed',
        },
        noImageText: {
            fontSize: 12,
            color: isDark ? '#64748B' : '#94A3B8',
        },
        modalBackdrop: {
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.85)',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 20,
        },
        centeredImageContainer: {
            width: '100%',
            maxWidth: 400,
            backgroundColor: '#000',
            borderRadius: 20,
            overflow: 'hidden',
            position: 'relative',
        },
        modalImageHeader: {
            position: 'absolute',
            top: 15,
            right: 15,
            zIndex: 10,
        },
        closeCircle: {
            backgroundColor: 'rgba(0,0,0,0.5)',
            width: 40,
            height: 40,
            borderRadius: 20,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.3)',
        },
        modalFullImage: {
            width: '100%',
            aspectRatio: 1,
            borderRadius: 20,
        },
        subActivityHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingVertical: 12,
            marginTop: 4,
        },
        unitRemarkContainer: {
            marginBottom: 16,
            padding: 12,
            borderRadius: 12,
            borderWidth: 1,
            borderLeftWidth: 5,
            borderLeftColor: '#10B981',
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: isDark ? 0.2 : 0.05,
            shadowRadius: 3,
            elevation: 2,
        },
        unitRemarkInput: {
            borderRadius: 8,
            padding: 10,
            height: 65,
            fontSize: 13,
            textAlignVertical: 'top',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            backgroundColor: isDark ? '#1E2130' : '#FFFFFF',
            color: isDark ? '#E2E8F0' : '#000000',
        },
        unitActionRow: {
            flexDirection: 'row',
            gap: 10,
            marginTop: 8,
            marginBottom: 12,
            alignItems: 'center',
        },
        unitActionButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: 6,
            backgroundColor: isDark ? '#2E3147' : '#F8FAFC',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            gap: 6,
        },
        unitActionText: {
            fontSize: 11,
            fontWeight: '700',
            color: isDark ? '#94A3B8' : '#64748B',
        },
        subActivityHeaderRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            marginBottom: 10,
        },
        subActivityActions: {
            flexDirection: 'row',
            gap: 5,
            justifyContent: 'center',
            alignItems: 'center',
        },
        subActivityMetricsGrid: {
            flexDirection: 'row',
            backgroundColor: isDark ? '#2E3147' : '#F8FAFC',
            borderRadius: 8,
            paddingVertical: 8,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#F1F5F9',
        },
        subMetricItem: {
            flex: 1,
            alignItems: 'center',
        },
        subMetricValue: {
            fontSize: 13,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#0F172A',
        },
        unitText: {
            fontSize: 9,
            fontWeight: '400',
            color: isDark ? '#64748B' : '#94A3B8',
        },
        subActivityFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: 8,
            paddingTop: 8,
            borderTopWidth: 1,
            borderTopColor: isDark ? '#3A3D4E' : '#F1F5F9',
        },
        footerInfoText: {
            fontSize: 11,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: '600',
        },
        materialBadge: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? '#0C3340' : '#ECFEFF',
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
            gap: 4,
        },
        materialBadgeOrange: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? '#2D1A00' : '#FFF7ED',
            paddingHorizontal: 8,
            paddingVertical: 3,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: isDark ? '#7C4010' : '#FED7AA',
            gap: 4,
        },
        materialTextOrange: {
            fontSize: 10,
            color: isDark ? '#FB923C' : '#C2410C',
            fontWeight: '800',
            letterSpacing: 0.3,
        },
        materialText: {
            fontSize: 10,
            color: isDark ? '#22D3EE' : '#0891B2',
            fontWeight: '700',
        },
        unitSelectorTab: {
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 20,
            backgroundColor: isDark ? '#2E3147' : '#E5E7EB',
        },
        unitSelectorTabActive: { backgroundColor: '#16A34A' },
        unitSelectorTabText: {
            fontSize: 13,
            color: isDark ? '#94A3B8' : '#374151',
            fontWeight: '600',
        },
        unitSelectorTabTextActive: { color: '#FFFFFF' },
        rowBetween: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        flexRowCenter: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        unitPickerButton: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? '#1E3A5F' : '#F0F7FF',
            paddingHorizontal: 12,
            paddingVertical: 8,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: '#007AFF',
        },
        unitPickerButtonText: {
            color: '#007AFF',
            fontSize: 12,
            fontWeight: '800',
        },
        modalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 20,
            paddingBottom: 12,
            borderBottomWidth: 1,
            borderBottomColor: isDark ? '#3A3D4E' : '#E5E7EB',
        },
        dropdownItem: {
            paddingVertical: 14,
            paddingHorizontal: 16,
            borderRadius: 10,
            marginBottom: 4,
            borderBottomWidth: 0.5,
            borderBottomColor: isDark ? '#3A3D4E' : '#F1F5F9',
        },
        weightageValidation: {
            padding: 10,
            borderRadius: 8,
            marginVertical: 12,
            alignItems: 'center',
            borderWidth: 1,
            borderStyle: 'dashed',
        },
        subActivityEditCard: {
            padding: 14,
            backgroundColor: isDark ? '#252836' : '#F9FAFB',
            borderRadius: 14,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E5E7EB',
            marginBottom: 12,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: isDark ? 0.2 : 0.05,
            shadowRadius: 2,
            elevation: 2,
        },
        subActionIconCircle: {
            width: 28,
            height: 28,
            borderRadius: 16,
            backgroundColor: isDark ? '#2E3147' : '#FFF',
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
        },
        subActivityName: {
            fontSize: 15,
            fontWeight: '700',
            color: isDark ? '#E2E8F0' : '#1E293B',
            marginBottom: 4,
        },
        metricsGrid: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            backgroundColor: isDark ? '#2E3147' : '#FFF',
            padding: 12,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
        },
        subMetricLabel: {
            fontSize: 10,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: '800',
            textTransform: 'uppercase',
            marginBottom: 4,
        },
        metricValue: {
            fontSize: 14,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#0F172A',
        },
        weightInput: {
            borderWidth: 1.5,
            borderColor: isDark ? '#3A3D4E' : '#CBD5E1',
            borderRadius: 8,
            padding: 8,
            width: 60,
            textAlign: 'center',
            backgroundColor: isDark ? '#1E2130' : '#FFF',
            fontSize: 14,
            fontWeight: 'bold',
            color: '#007AFF',
        },
        disabledInput: {
            backgroundColor: isDark ? '#2E3147' : '#F1F5F9',
            color: isDark ? '#64748B' : '#94A3B8',
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
        },
        addInlineButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            padding: 14,
            borderWidth: 1.5,
            borderColor: '#10B981',
            borderStyle: 'dashed',
            borderRadius: 12,
            marginTop: 10,
            gap: 8,
            backgroundColor: isDark ? '#0D2B1F' : '#F0FDF4',
        },
        subActivityRemarkBox: {
            marginTop: 12,
            padding: 12,
            borderRadius: 10,
            backgroundColor: isDark ? '#1E2130' : '#FFF',
            borderWidth: 1,
            borderColor: '#007AFF',
            borderStyle: 'dashed',
        },
        closeCircleSmall: {
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        unitIconCircle: {
            width: 30,
            height: 30,
            borderRadius: 15,
            justifyContent: 'center',
            alignItems: 'center',
        },
        materialModalContent: {
            backgroundColor: isDark ? '#252836' : '#FFF',
            width: '100%',
            maxWidth: 400,
            borderRadius: 16,
            padding: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: isDark ? 0.3 : 0.1,
            shadowRadius: 10,
            elevation: 5,
        },
        materialModalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 20,
        },
        materialModalTitle: {
            fontSize: 18,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#1E293B',
        },
        materialModalSubTitle: {
            fontSize: 14,
            color: isDark ? '#94A3B8' : '#64748B',
            marginTop: 4,
        },
        fieldContainer: { marginBottom: 16 },
        fieldLabel: {
            fontSize: 14,
            fontWeight: '600',
            color: isDark ? '#94A3B8' : '#334155',
            marginBottom: 8,
        },
        fieldInput: {
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#CBD5E1',
            borderRadius: 8,
            padding: 12,
            fontSize: 15,
            color: isDark ? '#E2E8F0' : '#1E293B',
            backgroundColor: isDark ? '#1E2130' : '#FFFFFF',
        },
        materialModalFooter: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 10,
        },
        modalBtn: {
            flex: 1,
            height: 48,
            borderRadius: 8,
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'row',
        },
        saveBtn: { backgroundColor: '#009640' },
        cancelBtn: { backgroundColor: isDark ? '#2E3147' : '#E2E8F0' },
        saveBtnText: { color: '#FFF', fontWeight: '700', marginLeft: 6 },
        cancelBtnText: {
            color: isDark ? '#94A3B8' : '#334155',
            fontWeight: '700',
        },
        mapLoadingOverlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: isDark ? 'rgba(30,33,48,0.97)' : 'rgba(255,255,255,0.95)',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 9999,
        },
        loaderContainer: {
            alignItems: 'center',
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            padding: 30,
            borderRadius: 20,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: isDark ? 0.3 : 0.1,
            shadowRadius: 12,
            elevation: 8,
            minWidth: 200,
        },
        loaderText: {
            marginTop: 16,
            fontSize: 18,
            fontWeight: '700',
            color: isDark ? '#E2E8F0' : '#1E293B',
        },
        addMaterialTrigger: {
            backgroundColor: '#009640',
            width: 22,
            height: 22,
            borderRadius: 22,
            justifyContent: 'center',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 3,
            elevation: 4,
        },
        addMaterialTriggerText: {
            color: '#FFFFFF',
            fontWeight: 'bold',
            fontSize: 13,
            marginLeft: 4,
        },
        cumulativeCard: {
            backgroundColor: isDark ? '#252836' : '#F8FAFC',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            marginBottom: 20,
            padding: 16,
            borderRadius: 14,
        },
        cumulativeHeaderTitle: {
            fontSize: 13,
            fontWeight: '900',
            color: isDark ? '#94A3B8' : '#475569',
            letterSpacing: 1,
            textAlign: 'center',
        },
        usageRow: { marginBottom: 15 },
        usageItemLabel: {
            fontSize: 12,
            fontWeight: '700',
            color: isDark ? '#E2E8F0' : '#1E293B',
        },
        usagePercentageText: {
            fontSize: 12,
            fontWeight: '800',
        },
        usageBarBackground: {
            height: 6,
            backgroundColor: isDark ? '#2E3147' : '#E2E8F0',
            borderRadius: 3,
            marginVertical: 6,
            overflow: 'hidden',
        },
        usageBarFill: {
            height: '100%',
            borderRadius: 3,
        },
        usageSubStats: {
            fontSize: 10,
            color: isDark ? '#64748B' : '#64748B',
            fontWeight: '600',
        },
        layerContainerCard: {
            borderRadius: 12,
            borderWidth: 1,
            padding: 14,
            marginBottom: 12,
            marginHorizontal: 2,
            elevation: 2,
        },
        allLayersCard: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: 15,
            borderRadius: 12,
            marginBottom: 15,
        },
        layerCardHeaderRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 16,
            borderBottomWidth: 1,
            borderBottomColor: isDark ? '#3A3D4E' : '#F1F5F9',
            paddingBottom: 8,
        },
        layerTitleText: {
            fontSize: 15,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#0F172A',
        },
        statusToggleButton: {
            paddingHorizontal: 12,
            paddingVertical: 4,
            borderRadius: 15,
            minWidth: 50,
            alignItems: 'center',
        },
        statusToggleText: {
            color: '#FFF',
            fontSize: 11,
            fontWeight: '900',
        },
        symbologyListContainer: { gap: 10 },
        symbologyRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        symbolIconWrapper: {
            width: 30,
            height: 20,
            justifyContent: 'center',
            alignItems: 'center',
        },
        symbologyLabel: {
            fontSize: 13,
            fontWeight: '500',
            color: isDark ? '#E2E8F0' : '#374151',
        },
        lineSymbolDraw: { width: 24, height: 2 },
        circleSymbolDraw: {
            width: 12,
            height: 12,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: 'rgba(0,0,0,0.2)',
        },
        outerCircleDraw: {
            width: 16,
            height: 16,
            borderRadius: 8,
            justifyContent: 'center',
            alignItems: 'center',
        },
        innerCircleDraw: {
            width: 8,
            height: 8,
            borderRadius: 4,
            borderWidth: 1,
            borderColor: '#FFF',
        },
        dashedLineContainer: {
            flexDirection: 'row',
            gap: 2,
        },
        dash: { width: 4, height: 2 },
        previousImageContainer: {
            position: 'relative',
            borderRadius: 10,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
        },
        previousImage: {
            width: 120,
            height: 120,
            backgroundColor: isDark ? '#2E3147' : '#F1F5F9',
        },
        imageDateBadge: {
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            backgroundColor: 'rgba(0,0,0,0.5)',
            paddingVertical: 4,
            alignItems: 'center',
        },
        imageDateText: {
            color: '#FFF',
            fontSize: 10,
            fontWeight: '600',
        },
        verifiedContainer: {
            marginTop: 8,
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'center',
        },
        verifiedText: {
            color: '#28a745',
            fontSize: 14,
            fontWeight: '600',
        },
        checkboxBase: {
            width: 24,
            height: 24,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 10,
            borderRadius: 6,
            borderWidth: 2,
            borderColor: '#10B981',
            backgroundColor: 'transparent',
        },
        checkboxBase2: {
            width: 24,
            height: 24,
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: 6,
            borderWidth: 2,
            borderColor: '#10B981',
            backgroundColor: 'transparent',
        },
        checkboxChecked: { backgroundColor: '#10B981' },
        inlineBtn: {
            flex: 1,
            height: 35,
            borderRadius: 6,
            justifyContent: 'center',
            alignItems: 'center',
        },
        verticalMetricsContainer: {
            backgroundColor: isDark ? '#252836' : '#FFFFFF',
            borderRadius: 12,
            borderWidth: 1,
            borderColor: isDark ? '#3A3D4E' : '#E2E8F0',
            overflow: 'hidden',
        },
        verticalMetricRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderBottomWidth: 1,
            borderBottomColor: isDark ? '#3A3D4E' : '#F1F5F9',
        },
        metricLabelGroup: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
        },
        indicatorDot: {
            width: 8,
            height: 8,
            borderRadius: 4,
        },
        verticalMetricLabel: {
            fontSize: 14,
            color: isDark ? '#94A3B8' : '#475569',
            fontWeight: '600',
        },
        verticalMetricInputArea: {
            minWidth: 70,
            alignItems: 'flex-end',
        },
        verticalMetricValue: {
            fontSize: 15,
            fontWeight: '800',
            color: isDark ? '#E2E8F0' : '#0F172A',
        },
        subActivityRowHighlight: {
            backgroundColor: isDark ? '#1E3A5F' : '#F0F7FF',
            borderBottomWidth: 0,
        },
        subPillDisplay: {
            paddingVertical: 4,
            paddingHorizontal: 10,
            borderRadius: 8,
            backgroundColor: '#007AFF',
            alignItems: 'center',
        },
        subPillText: {
            fontSize: 13,
            fontWeight: '900',
            color: '#FFFFFF',
        },
        loaderSubText: {
            marginTop: 4,
            fontSize: 13,
            color: isDark ? '#94A3B8' : '#64748B',
            fontWeight: '500',
        },
        spinnerWrapper: { marginBottom: 12 },
        mapIconCircle: {
            width: 60,
            height: 60,
            borderRadius: 30,
            backgroundColor: isDark ? '#1E3A5F' : '#EBF5FF',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 16,
        },
        progressDots: {
            flexDirection: 'row',
            gap: 8,
            marginTop: 16,
        },
        dotActive: { backgroundColor: '#007AFF' },
        imageGalleryCard: {
            width: '100%',
            height: '100%',
            borderRadius: 8,
            borderWidth: 1,
            overflow: 'hidden',
            justifyContent: 'center',
            alignItems: 'center',
        },
        failContainer: {
            padding: 10,
            alignItems: 'center',
        },
        failText: {
            color: isDark ? '#64748B' : '#8E8E93',
            fontSize: 14,
            fontWeight: '500',
        },
        latestBadgeContainer: {
            position: 'absolute',
            top: 8,
            left: 8,
            backgroundColor: '#16A34A',
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            zIndex: 10,
        },
        latestBadgeText: {
            color: '#FFFFFF',
            fontSize: 11,
            fontWeight: 'bold',
        },
        mapTypeIndicator: {
            position: 'absolute',
            top: 12,
            alignSelf: 'center',
            backgroundColor: 'rgba(15, 23, 42, 0.7)',
            paddingHorizontal: 12,
            paddingVertical: 4,
            borderRadius: 20,
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.2)',
            pointerEvents: 'none',
        },
        mapTypeIndicatorText: {
            color: '#FFFFFF',
            fontSize: 12,
            fontWeight: '700',
            textTransform: 'uppercase',
            letterSpacing: 0.5,
        },
        deleteBadgeStyle: {
            position: 'absolute',
            top: 6,
            right: 6,
            backgroundColor: '#EF4444',
            width: 30,
            height: 30,
            borderRadius: 15,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: '#FFF',
            zIndex: 99,
            elevation: 6,
        },
    });